[tool.poetry]
name = "starlight"
version = "0.1.0"
description = "An astrological chart tool."
authors = ["Kate Louie <katehlouie@gmail.com>"]
readme = "README.md"
packages = [{include = "starlight", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11.4"
pytest = "^7.4.0"
black = "^23.7.0"
pendulum = "^2.1.2"
skyfield = "^1.46"
pyswisseph = "^2.10.3.2"
svg-py = "^1.4.2"
isort = "^5.12.0"
mypy = "^1.4.1"
ruff = "^0.0.280"
svgwrite = "^1.4.3"
rich = "^13.9.4"
<<<<<<< HEAD
=======
geopy = "^2.4.1"
pytz = "^2025.1"
timezonefinder = "^6.5.8"
>>>>>>> master


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
